import { EmploymentType, EmployeeRole } from '../../common/enums/enums';

export const employeesSeed = [
  {
    externalCode: 1001,
    firstName: 'James',
    lastName: 'Smith',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1002,
    firstName: 'Emma',
    lastName: 'Johnson',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1003,
    firstName: 'Oliver',
    lastName: 'Williams',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1004,
    firstName: 'Sophia',
    lastName: 'Brown',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1005,
    firstName: 'William',
    lastName: 'Jones',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1006,
    firstName: 'Ava',
    lastName: 'Garcia',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1007,
    firstName: 'Jack',
    lastName: 'Miller',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1008,
    firstName: 'Mia',
    lastName: 'Davis',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1009,
    firstName: 'Lucas',
    lastName: 'Wilson',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1010,
    firstName: 'Isabella',
    lastName: 'Anderson',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1011,
    firstName: 'Henry',
    lastName: 'Thomas',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1012,
    firstName: 'Charlotte',
    lastName: 'Taylor',
    employmentType: EmploymentType.FULL_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'DESSERT',
  },
  {
    externalCode: 1013,
    firstName: 'Ethan',
    lastName: 'Moore',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1014,
    firstName: 'Amelia',
    lastName: 'Jackson',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1015,
    firstName: 'Mason',
    lastName: 'Martin',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1016,
    firstName: 'Harper',
    lastName: 'Lee',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1017,
    firstName: 'Logan',
    lastName: 'Thompson',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1018,
    firstName: 'Evelyn',
    lastName: 'White',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1019,
    firstName: 'Alex',
    lastName: 'Harris',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1020,
    firstName: 'Abigail',
    lastName: 'Clark',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1021,
    firstName: 'Michael',
    lastName: 'Lewis',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1022,
    firstName: 'Emily',
    lastName: 'Walker',
    employmentType: EmploymentType.PART_TIME,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'DESSERT',
  },
  {
    externalCode: 1023,
    firstName: 'Daniel',
    lastName: 'Hall',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1024,
    firstName: 'Elizabeth',
    lastName: 'Allen',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1025,
    firstName: 'Matthew',
    lastName: 'Young',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1026,
    firstName: 'Sofia',
    lastName: 'King',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1027,
    firstName: 'Samuel',
    lastName: 'Wright',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1028,
    firstName: 'Avery',
    lastName: 'Scott',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'KITCHEN',
  },
  {
    externalCode: 1029,
    firstName: 'David',
    lastName: 'Green',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1030,
    firstName: 'Ella',
    lastName: 'Baker',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1031,
    firstName: 'Joseph',
    lastName: 'Adams',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1032,
    firstName: 'Scarlett',
    lastName: 'Nelson',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1033,
    firstName: 'Ben',
    lastName: 'Hill',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1034,
    firstName: 'Grace',
    lastName: 'Campbell',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1035,
    firstName: 'Ryan',
    lastName: 'Mitchell',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1036,
    firstName: 'Chloe',
    lastName: 'Roberts',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'COUNTER',
  },
  {
    externalCode: 1037,
    firstName: 'Andrew',
    lastName: 'Carter',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1038,
    firstName: 'Victoria',
    lastName: 'Phillips',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'MCCAFE',
  },
  {
    externalCode: 1039,
    firstName: 'Nathan',
    lastName: 'Evans',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'DESSERT',
  },
  {
    externalCode: 1040,
    firstName: 'Madison',
    lastName: 'Turner',
    employmentType: EmploymentType.CASUAL,
    role: EmployeeRole.CREW,
    defaultStoreCode: 'Store_1',
    defaultStationCode: 'DESSERT',
  },
];
