export const shiftCodesSeed = [
  {
    code: 'S',
    shiftName: 'Day Shift',
    startTime: '06:30',
    endTime: '15:00',
    hours: 8.5,
    description: 'Opening and morning supervision',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: '1F',
    shiftName: 'First Half',
    startTime: '06:30',
    endTime: '15:30',
    hours: 9,
    description: 'Morning opening through lunch',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: '2F',
    shiftName: 'Second Half',
    startTime: '14:00',
    endTime: '23:00',
    hours: 9,
    description: 'Afternoon through closing',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: '3F',
    shiftName: 'Full Day',
    startTime: '08:00',
    endTime: '20:00',
    hours: 12,
    description: 'Extended all-day coverage',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: 'SC',
    shiftName: 'Shift Change',
    startTime: '11:00',
    endTime: '20:00',
    hours: 9,
    description: 'Peak overlap period',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: 'M',
    shiftName: 'Meeting',
    startTime: null,
    endTime: null,
    hours: 8,
    description: 'Management meetings/training',
    isAvailable: true,
    isManagement: true,
  },
  {
    code: '/',
    shiftName: 'Day Off',
    startTime: null,
    endTime: null,
    hours: 0,
    description: 'Rest day',
    isAvailable: false,
    isManagement: true,
  },
  {
    code: 'NA',
    shiftName: 'Not Available',
    startTime: null,
    endTime: null,
    hours: 0,
    description: 'Leave or vacation',
    isAvailable: false,
    isManagement: true,
  },
];

